[tool.isort]
line_length = 79

[tool.autopep8]
max_line_length = 79
ignore = E731
indent_size = 2

[tool.pylint]
indent-string = "  "
disable = [comprehension-escape, redefined-outer-name, invalid-name,
           unused-wildcard-import, unsubscriptable-object,
           cell-var-from-loop, redefined-builtin, missing-function-docstring,
           multiple-statements, wildcard-import, ]  # ! needs trailing comma
notes = [XXX, TODO,]  # ! needs trailing comma

max-line-length = 100
max-module-lines = 4000

max-args = 10
max-locals = 35
max-statements = 100
max-attributes = 30
min-public-methods = 1

variable-naming-style = any
class-naming-style = PascalCase
module-naming-style = snake_case
class-attribute-naming-style = any
method-naming-style = snake_case
function-naming-style = snake_case
argument-naming-style = snake_case
const-naming-style = UPPER_CASE
